### ISSUE TITLE
Attributes vs Basic Attributes vs Secondary Characteristics

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#11]
Currently, the Attribute enum contains the 4 main attributes, plus two secondary characteristics. (will & per)
This is probably because the trigger for the introduction of this enum was the controllingAttribute for skills, which typically is one of these six values.

Some questions come to mind:
- Should we be more strict and have both ' Basic Attributes'  and ' Secondary Characteristics' as given in the book?
- Why does the enum now contain values ' ST' and 'HT' and not their full values 'strength' and 'health'? It appears to me that the TLA's are just common shorthand, used for the output sheet and input xmls.

**Comment by dvberkel** [comment]
With respect to 'Basic Attributes' and 'Secondary Characteristics', I think I do not favour strictness here. The reason being that it is unclear what it would buy us, and it will certainly will cost us when we want to calculate skill levels.

Regarding 'ST' and 'HT', I have no strong opinion. Both variants are used in the book, although I think you see 'ST' more often

**Comment by mgoris** [comment]
Agreed on the strictness. Could we then add the secondary characteristics to the attributes as well?

I prefer the use of the full names of ST in the domain

**Comment by mgoris** [comment]
Implemented a compromise of the suggestions above.
See my commits on 26-11-2016
