### ISSUE TITLE
Add comments with page references to 4th edition when helpful?

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#12]
How do you feel about adding short comments in the code that references the basic books?
In my opinion, this can be especially helpful for cases where calculations or exceptional rules are implemented.
For example when capping or rounding values.

**Comment by dvberkel** [comment]
The question of comments is one that crops up often. I am definitely in [Uncle Bobs](https://twitter.com/unclebobmartin?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) camp, which frown upon comments in code. See for example [clean code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882).

In short his and other arguments are

1. Comments in code deteriorate over time. This create a maintenance burden and developers are very good at maintaining, especially comments.
2. Comments aren't compile checked, so they can claim false things and half truths.
3. Developers have a hard time to express them selves in code, so why do you think that they can clearly an concisely express them selves in comments.

On the other hand, I see why one would be interested why a certain rule is implemented in the way it is. I just think that comments aren't ideal to convey the motivation

**Comment by mgoris** [comment]
Okay. Let's see how far we get without comments and using well-readable descriptive code.
