### ISSUE TITLE
Add the attribute_bonus information to the advantage repository for further use

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#13]
We need the attribute_bonus information from the advantages.basic-set.xml in order to be able to apply these bonuses to the corresponding attributes when such advantages are added.

**Comment by mgoris** [comment]
Some changes for this were already introduced with https://github.com/gurpsdomain/gurpsdomain/commit/0398b84e9cde838ae8487106b7b50f1f0e598272

**Comment by dvberkel** [comment]
Although there are some details left to fill in, they are individually targeted in different issue. Closing this one to focus on the others
