### ISSUE TITLE
Boolean parameters are frowned upon

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#16]
In commit d5b546d1f6c75b4320670fb7c49994e731a43582 Attribute enum could a set of boolean parameters. In [FlagArgument](http://martinfowler.com/bliki/FlagArgument.html) Martin Fowler eloquently expresses why this is frowned upon.

We should try to find an alternative to boolean parameters

**Comment by mgoris** [comment]
"Clean Code" is to be delivered today by bol.com
To be unboxed on friday during sinterklaas. :)

**Comment by mgoris** [comment]
In this case, it concerns the constructor for the enum, which is always private if I understand correctly. This way I do not expose these flags. Correct?

**Comment by mgoris** [comment]
Removed the boolean parameters.
