### ISSUE TITLE
Law of demeter is broken for in Skill

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#17]
In commit 0a4e8dc372c83578029ae271b21c45ca80281410 the [law of demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) is broken, i.e. the code does not adhere to tell, don't ask principle. Specifically

```java
for (Attribute attribute : Attribute.values()) {
  if (attribute.isControlling()) {
    controllingAttributeMap.put(attribute.getShorthand(), attribute);
  }
}
```

Found on [line 31](https://github.com/gurpsdomain/gurpsdomain/commit/0a4e8dc372c83578029ae271b21c45ca80281410#diff-5627aae1bedc9d975820a97b9a267c95R31)

**Comment by mgoris** [comment]
Ok

**Comment by mgoris** [comment]
How would one obey to this law in this case? Have some sort of addToControllingAttributeMap method on Attribute that adds 'this' to the map if it is a controllingAttribute?

**Comment by mgoris** [comment]
Applied Demeter's Law for the case in the issue.
