### ISSUE TITLE
Merge ReflectionReader and ReflectionCaller

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#20]
This classes have similar characteristic, put the can not easily mixed.

**Comment by mgoris** [comment]
I see your point. Lots of similar code. 
Perhaps introduce a ReflectionOperator that implements the private 'operations' (i.e. call and read) of which subclasses can add their respective 'of' and 'from' methods?

**Comment by dvberkel** [comment]
I have had similar thoughts. I will see how far I can take this

**Comment by mgoris** [comment]
Merge and refactor was done in https://github.com/gurpsdomain/gurpsdomain/commit/dad23bb28ed926d3c70abfa2674146752653b2b8
