### ISSUE TITLE
AddAdvantagesStep has a attributeBonus gathering phase

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#25]
To me it seems a mistake to gather very specific effects, i.e. attribute bonusses, while creating an advantage. I would rather see that the effects an advantage has is inherently to the advantage. A user should not have to address them in the input.

Furthermore attribute bonus are far to specific to my taste.

Let's discuss this.

**Comment by mgoris** [comment]
Very true and well spotted. Seems like a mistake indeed. Removed them in 1bc72763c0dd0f168b1e2ae7b61ddb6598966736

**Comment by mgoris** [comment]
Ah, just learned something by accident on automatic links from commit messages :)
