### ISSUE TITLE
Attribute has method that throw explicit RuntimeException

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#26]
While working on incorporating bonuses of  attributes, I delayed the decision how to handle non-integer bonus for attributes like basic lift bonus etcetera.

I opted to just throw a runtime exception and deal with it a later moment.

This issue is a constant reminder

**Comment by mgoris** [comment]
integer and double attribute bonuses are now supported. Other type bonuses still throw the runtime exception. However, these do not seem to appear in the xml, but perhaps in other books.

**Comment by dvberkel** [comment]
Lets close this, and deal with it when we run into problems
