### ISSUE TITLE
Attribute alternative description should be provided

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#27]
In order to create an `AttributeBonus` from an `AttributeBonusDescription` we need a way to look up an `Attribute` from a description found in the XML. For this the `Attribute` bonus got an `alternativeDescription`, i.e. a variable length constructor argument, detailing alternative ways of getting an `Attribute.fromDescription`.

I only provide strength and intelligence. The others should be provided with the identifiers found in the XML.

**Comment by mgoris** [comment]
Identified the following values from the xml. Will handle them.
```
<attribute>hearing</attribute>
<attribute>taste smell</attribute>
<attribute>touch</attribute>
<attribute>vision</attribute>
<attribute limitation="lifting only">st</attribute>
<attribute>dodge</attribute>
<attribute>parry</attribute>
<attribute>block</attribute>
<attribute>fright check</attribute>
<attribute>move</attribute>
<attribute>speed</attribute>
<attribute>dx</attribute>
<attribute>ht</attribute>
<attribute>iq</attribute>
<attribute>perception</attribute>
<attribute>st</attribute>
<attribute>will</attribute>
<attribute>sm</attribute>
<attribute>fp</attribute>
<attribute>hp</attribute>
<attribute limitation="striking only">st</attribute>

```

**Comment by mgoris** [comment]
Last few missing descriptions can not be added, as there are no attributes implemented yet for them. Updated the issue #28 with these missing items. Close this issue.
