### ISSUE TITLE
Parry is not an attribute yet

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/gurpsdomain#28]
While working on attribute bonuses I ran into a problem with the scenario test.

There *Combat Reflexes* is added, which gives a bonus to parry. Unfortunately  parry is not an attribute yet.

It needs to be added in order to include the scenario again. I commented it out for my convenience in commit 9976fed9f81d45232bb137e4e231ccc3a270e0eb

**Comment by mgoris** [comment]
While working on #27 I found some more missing attributes:
```
<attribute limitation="lifting only">st</attribute>
<attribute>dodge</attribute>
<attribute>parry</attribute>
<attribute>block</attribute>
<attribute>fright check</attribute>
<attribute>sm</attribute>
<attribute limitation="striking only">st</attribute>
```

**Comment by mgoris** [comment]
Thinking about the mentioned missing attributes above, I actually feel that:
- dodge is a true attribute
- block and parry are no true attributes, as they vary per weapon / skill
- fright check is a true attribute
- sm is a true attribute
- lifting and striking strengths are true attributes. ( derivatives of strength )

**Comment by dvberkel** [comment]
Your use of *true* is ambiguous. Did you mean *primary* and *secondary*?

**Comment by mgoris** [comment]
true ;)
I mean that I don't feel it belongs in the attributes as we have them now.

**Comment by mgoris** [comment]
Added fright check in 630dde8e34b0880fdd4171209be412a60605d733

**Comment by dvberkel** [comment]
I say let's keep them in this form, until we better know what we want.
