### ISSUE TITLE
Add SpellBonus

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#30]
Similarly to AttributeBonus, a SpellBonus can be added.
This can be used to effect the magery levels in spell level determination.
Two occurences in xml:

Magery:
```
		<spell_bonus>
			<college_name compare="is">@College@</college_name>
			<amount per_level="yes">1</amount>
		</spell_bonus>
```

Magery again:
```
		<spell_bonus all_colleges="yes">
			<amount per_level="yes">1</amount>
		</spell_bonus>
```

**Comment by dvberkel** [comment]
This will be taken up in issue #33
