### ISSUE TITLE
Implement bonuses for Skills and Spells

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#31]
Bonuses for Skills and Spells are not implemented yet.

**Comment by mgoris** [comment]
Skill bonuses have been added today. However, in a simple form without taking specialization and comparing into account.
It needs a good review and also discussion on the way I tried to solve the 'order of processing' problem.
@dvberkel

**Comment by dvberkel** [comment]
Looks good to me
