### ISSUE TITLE
Determine goal json definition for integration of gurpsdomain and GurpsyMcGurpsface

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#34]
If we could determine a ' final'  json definition, we could start integrating both projects.
This would also make sure that we think about and decide upon the things we do/don't want.
@meronbrouwer @dvberkel

**Comment by meronbrouwer** [comment]
GurpsyMcGurpsFace will adapt...

**Comment by dvberkel** [comment]
I think `dai-blackthorn.json` in `src/test/resources/sheets/` is a good starting place. We could finalize it and ship it to GurpsyMcGurpsFace
