### ISSUE TITLE
It should not be possible for (point modified) advantages to have a negative cost

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#5]
We introduced point modifiers next to percentage modifiers, because these seem logical in the system.
However, in the GURPS books only percentage modifiers are known. What we use as point modifiers are in GURPS actually 'different' advantages.

At this moment, it is (theoretically) possible to reduce the effective cost of an advantage below to an integer below 0, by adding enough negative point modifiers.
This should not be possible because an advantage with a negative cost is actually  considered a disadvantage.

**Comment by dvberkel** [comment]
But is an advantage, when sufficiently modified not a disadvantage?

I am not sure that if this is a problem.

Especially, considering that the disadvantages are listed as advantages as well, just with a different category.

**Comment by mgoris** [comment]
I feel that your suggestion would be more in line with the current sheet-tool rather than the books. Advantages and Disadvantages are different things to me and one should not be transfered to another by adding enough modifiers.

However, I do agree that they are very alike and perhaps share a common 'parent'

**Comment by dvberkel** [comment]
I thinks we can have our cake and eat it two.

We could be differentiate advantages and disadvantages on the input yaml and output json, but not differentiate them in the domain.

This could have the added benefit that an advantages, suitably modified would migrate automatically to disadvantages, and vice versa.

**Comment by dvberkel** [comment]
I added a label to identify this policy. Because the discussion is made, I am closing this issue
