### ISSUE TITLE
The name of advantage modifiers is not unique in advantages.basic-set.xml

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#7]
The name of advantage modifiers is not unique in advantages.basic-set.xml
With the current implementation modifiers cannot be uniquely identified.

Proposal solution could be to concatenate the name with the notes during conversion.
Example of such a problematic Advantage:

```xml
....
	<advantage version="2">
		<name>Speak With Animals</name>
		<type>Mental, Exotic</type>
		<base_points>25</base_points>
		<modifier version="1" enabled="no">
			<name>Specialized</name>
			<cost type="percentage">-40</cost>
			<affects>total</affects>
			<reference>B87</reference>
			<notes>All aquatic animals</notes>
		</modifier>
		<modifier version="1" enabled="no">
			<name>Specialized</name>
			<cost type="percentage">-40</cost>
			<affects>total</affects>
			<reference>B87</reference>
			<notes>All land animals</notes>
		</modifier>
...
```

**Comment by dvberkel** [comment]
Well spotted.

Before we jump to a conclusion, let's see how we want to address this in the input yaml.

**Comment by mgoris** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have unique modifier names](https://trello.com/c/dAHcGrFr/3-have-unique-modifier-names)

**Comment by dvberkel** [comment]
@pebeling Could you think of a way to how to distinguish between different modifiers in the YAML?

Afterwards you could create a [`ModifierDescriptionPredicate`](https://github.com/gurpsdomain/gurpsdomain/blob/a142b838bb029d745d4d7ea96b357607686cd66d/src/main/java/org/gurpsdomain/domain/description/predicate/ModifierDescriptionPredicate.java) to match your ideas

**Comment by mgoris** [comment]
I made (and integrated) a first setup in my last two commits, to get clear where the problems will arise and which decisions need to be made.

My function viewpoint for now (not implemented in this way yet):
- User can use the identifying part of a modifier in the name field of the yaml. ( i.e. the actual name, or the note in some cases)
- We need to be able to uniquely identify a single modifier from that, if not -> problem
- The name in the json could then be 1) the actual name if unique, or 2) the "name - note" if the note is the unique identifier, or 3) just the note.

Open for input!

**Comment by dvberkel** [comment]
I also provided some comments in the mentioned commits.

I would strongly argue against 1 becoming the standard. We should rely be able to rely on the name of a modifier to be a name, not a name unless it is not unique then it is a note, oh wait I found an other case well lets hack it in there as well and live with it.
It is a slippery slope, that should be avoided. Add other fields that identify the modifer, e.g. a note.

Nothing to argue with with signalling a problem. The only side note is that we do signal errors at the moment. We should have a proper discussion about how we would want to do that. But it seems out of scope for this issue.

I also strongly would advocate against suggestion 3. I thoroughly dislike it, with the same reasons as stated by 1.

**Comment by dvberkel** [comment]
I would prefer that the yaml would look like

```yaml
- advantages
  - name: Speak With Animals
    modifiers:
    - name: Specialized
    - note: All aquatic animals
```

**Comment by mgoris** [comment]
Did some rework in 1937f5cc0b243f284a1e48b212758d959745b35c based on the above.
Chose 'variation' for use on the yaml rather than the ambiguous 'note'.
Referenced the books to see if there was any common semantics for this, but there was not so I introduced this one.

**Comment by dvberkel** [comment]
This solves this issue so I am closing it. There is some refactoring to do, but I am going to prepare that for @pebeling in a different issue.
